// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"base/app/providers/database"
	"base/app/providers/hash"
	"base/internal/user/respositories"
	"base/internal/user/services"
	"github.com/labstack/echo/v4"
)

// Injectors from injector.go:

func InitializeUserApi(echo2 *echo.Group, provider *database.Provider) IUserApi {
	iUserRepository := respositories.NewUserRepository(provider)
	iProvider := hash.NewHashProvider()
	iUserService := services.NewUserService(iUserRepository, iProvider)
	iUserApi := NewUserApi(echo2, iUserService)
	return iUserApi
}
