// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"base/app/config"
	"base/app/providers/database"
	"base/app/providers/hash"
	"base/internal/auth/repositories"
	"base/internal/auth/services"
	"base/internal/user/respositories"
	"base/utils/token"
	"base/utils/uuid"
	"github.com/labstack/echo/v4"
)

// Injectors from injector.go:

func InitializeAuthApi(echo2 *echo.Echo, provider *database.Provider, JwtConfig *config.JWT) IAuthApi {
	iUserRepository := respositories.NewUserRepository(provider)
	iProvider := hash.NewHashProvider()
	tokenIProvider := token.NewTokenProvider(JwtConfig)
	uuidIProvider := uuid.NewUuidProvider()
	iRefreshTokenRepository := repositories.NewRefreshTokenRepositories(provider)
	iAuthService := services.NewAuthService(iUserRepository, iProvider, tokenIProvider, uuidIProvider, iRefreshTokenRepository)
	iAuthApi := NewAuthAPi(echo2, iAuthService)
	return iAuthApi
}
